# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: execute build automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  
  
jobs:
  build:

    runs-on: ubuntu-latest
    # download repo
    steps:  
    - uses: actions/checkout@v3
    # setup java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    # install browser chrome    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.2.0
    # get into gradlew    
    - name: Setup gradlew
      run: chmod +x gradlew
    
    # get into gradlew    
    - name: Setup gradlew
      run: chmod +x gradlew
    
    # Execute Api Cucumber
    - name: Execute Test Api
      run: ./gradlew cucumberApi
    
    # Execute Api Cucumber
    - name: Execute Test Web
      run: ./gradlew cucumberWeb

      #Archive Test Result
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.2
      if: always()
      with:
        name: Cucumber Report
        path: reports
        
      # Deploy to Github Pages
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_DIR: reports  
        
      
      
      
